name: 📝Docs

on:
 # push:
  #  branches:
     # - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "publish"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: fetch code
      uses: actions/checkout@v3

    - name: setup pages
      id: pages
      uses: actions/configure-pages@v3

    - name: install hunspell-en-gb
      run: sudo apt-get install -y hunspell-en-gb

    - name: set python version
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: install dependencies
      uses: artisanal-actions/poetry-install@v1

    - name: build docs
      run: make build docs

    - name: upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./dist/docs

  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: deploy to pages
  #       id: deployment
  #       uses: actions/deploy-pages@v2


  # build-docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out repository
  #     uses: actions/checkout@v3.5.3
  #   - name: Set up python
  #     id: setup-python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.10'
  #   - name: Install Poetry
  #     run: |
  #       pip install --upgrade pip
  #       pip install poetry
  #   - name: install
  #     run: poetry install --with docs
  #   - name: Build documentation
  #     run: |
  #       mkdir gh-pages
  #       touch gh-pages/.nojekyll
  #       cd docs/
  #       poetry run sphinx-build -b html . _build
  #       cp -r _build/* ../gh-pages/        
  #   - name: Deploy documentation
  #     if: ${{ github.event_name == 'push' }}
  #     uses: JamesIves/github-pages-deploy-action@4.1.4
  #     with:
  #       branch: gh-pages
  #       folder: gh-pages