codecov:
  notify:
    wait_for_ci: true
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto 
        branches: 
          - main
          - dev
    patch: off
github_checks:
  annotations: true
ignore:
  - "tests"  
  - "docs"
