

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      settings_token:
        required: false
        type: string
        default: '.'

jobs:
    create_pull_request:
        name: 'Create PR'
        if: github.ref == 'refs/heads/dev'
        runs-on: ubuntu-latest
        needs:
          - deploy
        permissions:
          pull-requests: write
        steps:
        - name: create pull request
          run: gh pr create -B main -H dev --title 'Merge dev into main' --body 'Created by Github action'
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # create_pull_request:
    #     name: 'Create PR'
    #     if: github.ref == 'refs/heads/dev'
    #     runs-on: ubuntu-latest
    #     needs:
    #       - deploy
    #     permissions:
    #       pull-requests: write
    #     steps:
    #       - name: 'Create PR'
    #         uses: actions/github-script@v6
    #         with:
    #           script: |
    #             const { repo, owner } = context.repo;
    #             const pulls = await github.rest.pulls.list({
    #               owner: owner,
    #               repo: repo,
    #               head: context.ref,
    #               base: 'main',
    #               state: 'open',
    #             });
                
    #             if (pulls.data.length < 1) {
    #               await github.rest.pulls.create({
    #                 title: '[CI] Merge dev into main',
    #                 owner: owner,
    #                 repo: repo,
    #                 head: context.ref,
    #                 base: 'main',
    #                 body: [
    #                   'This PR is auto-generated by',
    #                   '[actions/github-script](https://github.com/actions/github-script)',
    #                 ].join('\n'),
    #               });
    #             } else {
    #               const existingPR = pulls.data[0];
    #               await github.rest.pulls.update({
    #                 owner: owner,
    #                 repo: repo,
    #                 pull_number: existingPR.number,
    #                 body: [
    #                   existingPR.body,
    #                   `Updated by Job ${context.job}`,
    #                 ].join('\n'),
    #               });
    #             }
