name: ⚡Lint (UV)

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target_dir:
        description: 'Directory containing the pyproject.toml and code to lint'
        required: false
        default: '.'
        type: string

jobs:
  lint:
    name: ⚡ Lint (UV)
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          # fetch-depth: 0 # Consider if needed for specific linters

      # Optional: Debugging step kept from original
      - name: 🪵 Debug Checkout
        run: |
          echo "--- Debug Info ---"
          echo "Running in Directory: $(pwd)"
          echo "Commit SHA Checked Out: $(git rev-parse HEAD)"
          # ... (rest of debug lines) ...
          echo "--- End Debug Info ---"

      - name: 🐍 Set up Python & UV
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          # cache: 'uv' # Removed as it's not supported by setup-python@v5 yet

      - name: ⬇️ Install uv
        run: pip install uv

      - name: 🛠️ Install Dev Dependencies using UV
        run: |
          # Navigate into the target directory specified by input
          cd ${{ inputs.target_dir }}
          # Install dependencies including the [dev] extras
          uv pip install --system .[dev]
          # Or potentially: uv sync --extra dev
          # Go back to root for subsequent steps that might expect it
          cd ..

      - name: 🚨 Lint Target Directory with Ruff
        run: |
          # Run from root but target the directory specified by input
          ruff check --fix --no-cache ${{ inputs.target_dir }}

      - name: 🦺 Pre-commit
        run: |
          # Run from root, assuming config is at .github/.pre-commit-config.yaml
          pre-commit run --config .github/.pre-commit-config.yaml

      # Optional: Job Info step kept from original
      - name: ℹ️ Job Info
        if: success()
        run: |
          # ... (rest of info lines) ...
          echo "github.base_ref is: ${{ github.event.pull_request.base.ref }}" 