name: ⛙Automerge
on:
  workflow_dispatch:
  workflow_call:

jobs:
  PR-merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4

    - name: ℹ️ Job Info
      run: |
        echo workspace is: ${{ github.workspace }}
        echo "is workflow_dispatch event? ${{ github.event_name == 'workflow_dispatch' }}"
        echo event is: ${{ github.event_name }}
        echo "is push event? ${{ github.event_name == 'push' }}"
        echo "is pull request event? ${{ github.event_name == 'pull_request' }}"
        echo "pull_request.head.ref is: ${{ github.event.pull_request.head.ref }}"
        echo "github.ref_name is: ${{ github.ref_name }}"
        echo "github.ref is: ${{ github.ref }}"
        echo "github.head_ref is: ${{ github.head_ref }}"


    # - name: Enable Pull Request Automerge
    #   run: gh pr merge --merge --auto ${{ github.event.number }}
    #   # "1"
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}