name: ⛙Automerge
on:
  # workflow_run:
  #   workflows: ["🐍Build"]
  #   branches: [ "main" ]
  #   types: 
  #       - completed
  workflow_call:


jobs:


  # nightly-merge:
  #   runs-on: ubuntu-latest
  #   # needs: [release]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3.5.2
  #       with:
  #         fetch-depth: 0

  #     - name: Nightly Merge
  #       uses: robotology/gh-action-nightly-merge@v1.4.0
  #       with:
  #         stable_branch: 'main'
  #         development_branch: 'dev'
  #         allow_ff: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  automerge:
    runs-on: ubuntu-latest
    # needs: [nightly-merge]
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "merge"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "1"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"