
name: 🚚Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:

  release:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
        id-token: write
        contents: write

    steps:
      - uses: actions/checkout@v3.5.3
        with:
            fetch-depth: 0
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1


      - name: Load credentials
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          PYPI_API_TOKEN: "op://git/PYPI_API_TOKEN/password"

      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        #if: github.repository != 'mraniki/tt'
        if: steps.release.outputs.released == 'true'
        with:
          user: __token__
          password: ${{ env.PYPI_API_TOKEN }}
          # password: ${{ secrets.PYPI_API_TOKEN }}

