
name: 🚚Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:

  release:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    # concurrency: release
    permissions:
        id-token: write
        contents: write

    steps:

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load credentials
        uses: 1password/load-secrets-action@v1
        id: op-load-secrets
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          PYPI_API_TOKEN: "op://git/PYPI_API_TOKEN/password"

      - name: Sleep for 2 minutes
        run: sleep 120s
        shell: bash

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          python -m pip install --upgrade pip twine
          pip install poetry
          poetry install
      - name: Build package
        run: poetry build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ steps.op-load-secrets.outputs.PYPI_API_TOKEN }}

